port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_ES |16.52Mb
  server: 5.188.181.201
  type: ss
  port: 9025
  udp: true
  password: XPtzA9sCug3SPR4c
  cipher: aes-256-cfb
- name: netflix_CH |29.05Mb
  server: 51.15.23.63
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_TW |10.23Mb
  server: n8mrcg006016ehj.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_TW |11.13Mb
  server: n8mrcg0059867fh.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: Relay_-🇹🇼TW_78 |44.96Mb
  server: r3mrcg001162ctc.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_TW |10.45Mb
  server: n8mrcg005972g7w.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_TW |11.06Mb
  server: n8mrcg004697zw5.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_TW |10.35Mb
  server: r3mrcg007144ll4.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_TW |10.83Mb
  server: n8mrcg005988a7z.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |147.45Mb
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_TW |10.34Mb
  server: r3mrcg00129437x.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |57.56Mb
  server: 104.18.11.110
  type: trojan
  port: 443
  udp: true
  password: humanity
  sni: www.multiplydose.com
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
  network: ws
- name: disney_TW |10.70Mb
  server: n8mrcg004676x9e.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: _124 |36.93Mb
  server: 146.59.118.182
  type: vmess
  port: 443
  udp: true
  uuid: 0b72f4f7-55f3-4d83-92ae-e391f6523f44
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
    headers:
      Host:
      - 146.59.118.182
  h2-opts: {}
- name: disney_netflix_NL |38.69Mb
  server: 94.131.105.125
  type: trojan
  port: 4443
  udp: true
  password: strong-secret-pass-777
  skip-cert-verify: true
- name: disney_netflix_ES |160.67Mb
  server: 85.90.217.42
  type: vmess
  port: 22324
  udp: true
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TW |10.35Mb
  server: r3mrcg007116sfa.cybervena.com
  type: ss
  port: 50099
  udp: true
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: Relay_-🇩🇪DE_136 |259.23Mb
  server: dynamic-tiger.crayfish192.xyz
  type: trojan
  port: 443
  password: WF42809561
  sni: dynamic-tiger.crayfish192.xyz
- name: _132 |28.98Mb
  server: 20.6.128.4
  type: vmess
  port: 6788
  udp: true
  uuid: bfff8306-6102-4fde-8a7f-f025e94f7a53
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_NL |19.44Mb
  server: model-stingray.crayfish192.xyz
  type: trojan
  port: 443
  password: WF42809561
  sni: model-stingray.crayfish192.xyz
- name: disney_netflix_LV |16.93Mb
  server: 103.231.73.181
  type: trojan
  port: 4443
  udp: true
  password: strong-secret-pass-777
  skip-cert-verify: true
- name: Relay_-🇮🇪IE_150 |340.97Mb
  server: eternal-serval.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: eternal-serval.rooster465.autos
- name: Relay_-🇱🇺LU_155 |15.99Mb
  server: funky-platypus.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: funky-platypus.rooster465.autos
- name: disney_netflix_NL |21.84Mb
  server: touching-pigeon.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: touching-pigeon.rooster465.autos
- name: Relay_-🇮🇪IE_148 |308.42Mb
  server: grown-goldfish.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: grown-goldfish.rooster465.autos
- name: Relay_-🇮🇪IE_153 |330.36Mb
  server: optimal-dane.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: optimal-dane.rooster465.autos
- name: Relay_-🇺🇸US_164 |31.98Mb
  server: alert-sunbird.crayfish192.xyz
  type: trojan
  port: 443
  password: WF42809561
  sni: alert-sunbird.crayfish192.xyz
- name: disney_netflix_US |39.36Mb
  server: 160.16.70.180
  type: trojan
  port: 3700
  password: 6d29eb2f74293cb01a19b32cf08ad2e9
  sni: www.nintendogames.net
- name: Relay_-🇦🇺AU_151 |10.72Mb
  server: evolving-kangaroo.rooster465.autos
  type: trojan
  port: 443
  udp: true
  password: WF42809561
  sni: evolving-kangaroo.rooster465.autos
- name: Relay_-🇦🇺AU_160 |11.34Mb
  server: premium-lab.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: premium-lab.rooster465.autos
- name: Relay_-🇮🇪IE_145 |304.26Mb
  server: saving-anemone.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: saving-anemone.rooster465.autos
- name: disney_KR |10.24Mb
  server: powerful-squid.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: powerful-squid.rooster465.autos
- name: disney_KR |10.70Mb
  server: amused-peacock.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: amused-peacock.rooster465.autos
- name: Relay_-🇯🇵JP_168 |12.23Mb
  server: 160.16.124.17
  type: trojan
  port: 34818
  password: 6d29eb2f74293cb01a19b32cf08ad2e9
  sni: www.nintendogames.net
- name: Relay_🇧🇬 BG-🇦🇺AU_171 |11.62Mb
  server: enhanced-crayfish.rooster465.autos
  type: trojan
  country: 🇧🇬 BG
  port: 443
  udp: true
  password: IL37892054
  skip-cert-verify: true
- name: disney_KR |10.79Mb
  server: sterling-fowl.rooster465.autos
  type: trojan
  port: 443
  password: WF42809561
  sni: sterling-fowl.rooster465.autos
- name: disney_netflix_PL |134.47Mb
  server: fluent-stingray.crayfish192.xyz
  type: trojan
  country: 🇭🇺HU
  port: 443
  udp: true
  password: IL37892054
  sni: fluent-stingray.crayfish192.xyz
  skip-cert-verify: true
- name: Relay_🇭🇰HK-🇮🇩ID_180 |11.67Mb
  server: 47.57.182.141
  type: vmess
  country: 🇭🇰HK
  port: 443
  uuid: 462d9694-62b5-4781-a287-61a422b920e8
  alterId: 0
  cipher: auto
  network: ws
  servername: mn1ray.jagoanvip.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /vvip
    headers:
      HOST: mn1ray.jagoanvip.xyz
- name: disney_netflix_NL |27.88Mb
  server: 85.234.65.58
  type: trojan
  country: 🇬🇧GB
  port: 443
  udp: true
  password: WF42809561
  sni: touching-pigeon.rooster465.autos
  skip-cert-verify: true
- name: disney_netflix_HK |26.93Mb
  server: ready-monarch.rooster465.autos
  type: trojan
  port: 443
  udp: true
  password: WF42809561
  sni: ready-monarch.rooster465.autos
- name: netflix_JP |12.90Mb
  server: 45.12.134.57
  type: trojan
  country: 🇳🇱NL
  port: 4443
  udp: true
  password: strong-secret-pass-777
  skip-cert-verify: true
- name: Relay_🏁ZZ-🇰🇷KR_207 |28.32Mb
  server: c7.620720.xyz
  type: vmess
  country: 🏁ZZ
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: c7.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: c7.620720.xyz
- name: 🇰🇷KR_186 |112.60Mb
  server: 141.164.45.187
  type: ss
  country: 🇰🇷KR
  port: 5498
  password: lGqs95QkFHo2NV
  cipher: aes-256-gcm
- name: Relay_🇺🇸US-🇺🇸US_201 |32.21Mb
  server: healthy-ewe.rooster465.autos
  type: trojan
  country: 🇺🇸US
  port: 443
  udp: true
  password: IL37892054
  sni: healthy-ewe.rooster465.autos
  skip-cert-verify: true
- name: netflix_DK |25.13Mb
  server: 192.36.27.94
  type: ss
  country: 🇸🇪 SE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_KR |12.77Mb
  server: chuncheon03.zgjok.com
  type: vmess
  country: 🇰🇷KR
  port: 443
  uuid: 81d5cac4-d039-4874-9a20-c391f580012d
  alterId: 0
  cipher: auto
  network: ws
  servername: chuncheon03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: chuncheon03.zgjok.com
- name: disney_TW |10.41Mb
  server: nbmrcg003437cgb.cybervena.com
  type: ss
  country: 🇹🇼 TW
  port: 50099
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  cipher: chacha20-ietf-poly1305
- name: Relay_🇺🇸US-🇮🇩ID_200 |11.53Mb
  server: 47.130.9.238
  type: vmess
  country: 🇺🇸US
  port: 443
  uuid: 462d9694-62b5-4781-a287-61a422b920e8
  alterId: 0
  cipher: auto
  network: ws
  servername: mn1ray.jagoanvip.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /vvip
    headers:
      HOST: mn1ray.jagoanvip.xyz
- name: 🇭🇺HU_183 |28.34Mb
  server: 194.71.130.26
  type: ss
  country: 🇭🇺HU
  port: 2949
  password: v8NKiSxilGVslodFPWWLR8
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - ♻️ 自动选择
  - disney_netflix_ES |16.52Mb
  - netflix_CH |29.05Mb
  - disney_TW |10.23Mb
  - disney_TW |11.13Mb
  - Relay_-🇹🇼TW_78 |44.96Mb
  - disney_TW |10.45Mb
  - disney_TW |11.06Mb
  - disney_TW |10.35Mb
  - disney_TW |10.83Mb
  - disney_netflix_GB |147.45Mb
  - disney_TW |10.34Mb
  - disney_netflix_NL |57.56Mb
  - disney_TW |10.70Mb
  - _124 |36.93Mb
  - disney_netflix_NL |38.69Mb
  - disney_netflix_ES |160.67Mb
  - disney_TW |10.35Mb
  - Relay_-🇩🇪DE_136 |259.23Mb
  - _132 |28.98Mb
  - disney_netflix_NL |19.44Mb
  - disney_netflix_LV |16.93Mb
  - Relay_-🇮🇪IE_150 |340.97Mb
  - Relay_-🇱🇺LU_155 |15.99Mb
  - disney_netflix_NL |21.84Mb
  - Relay_-🇮🇪IE_148 |308.42Mb
  - Relay_-🇮🇪IE_153 |330.36Mb
  - Relay_-🇺🇸US_164 |31.98Mb
  - disney_netflix_US |39.36Mb
  - Relay_-🇦🇺AU_151 |10.72Mb
  - Relay_-🇦🇺AU_160 |11.34Mb
  - Relay_-🇮🇪IE_145 |304.26Mb
  - disney_KR |10.24Mb
  - disney_KR |10.70Mb
  - Relay_-🇯🇵JP_168 |12.23Mb
  - Relay_🇧🇬 BG-🇦🇺AU_171 |11.62Mb
  - disney_KR |10.79Mb
  - disney_netflix_PL |134.47Mb
  - Relay_🇭🇰HK-🇮🇩ID_180 |11.67Mb
  - disney_netflix_NL |27.88Mb
  - disney_netflix_HK |26.93Mb
  - netflix_JP |12.90Mb
  - Relay_🏁ZZ-🇰🇷KR_207 |28.32Mb
  - 🇰🇷KR_186 |112.60Mb
  - Relay_🇺🇸US-🇺🇸US_201 |32.21Mb
  - netflix_DK |25.13Mb
  - netflix_KR |12.77Mb
  - disney_TW |10.41Mb
  - Relay_🇺🇸US-🇮🇩ID_200 |11.53Mb
  - 🇭🇺HU_183 |28.34Mb
  url: https://www.google.com/generate_204
- name: ♻️ 自动选择
  type: url-test
  proxies:
  - disney_netflix_ES |16.52Mb
  - netflix_CH |29.05Mb
  - disney_TW |10.23Mb
  - disney_TW |11.13Mb
  - Relay_-🇹🇼TW_78 |44.96Mb
  - disney_TW |10.45Mb
  - disney_TW |11.06Mb
  - disney_TW |10.35Mb
  - disney_TW |10.83Mb
  - disney_netflix_GB |147.45Mb
  - disney_TW |10.34Mb
  - disney_netflix_NL |57.56Mb
  - disney_TW |10.70Mb
  - _124 |36.93Mb
  - disney_netflix_NL |38.69Mb
  - disney_netflix_ES |160.67Mb
  - disney_TW |10.35Mb
  - Relay_-🇩🇪DE_136 |259.23Mb
  - _132 |28.98Mb
  - disney_netflix_NL |19.44Mb
  - disney_netflix_LV |16.93Mb
  - Relay_-🇮🇪IE_150 |340.97Mb
  - Relay_-🇱🇺LU_155 |15.99Mb
  - disney_netflix_NL |21.84Mb
  - Relay_-🇮🇪IE_148 |308.42Mb
  - Relay_-🇮🇪IE_153 |330.36Mb
  - Relay_-🇺🇸US_164 |31.98Mb
  - disney_netflix_US |39.36Mb
  - Relay_-🇦🇺AU_151 |10.72Mb
  - Relay_-🇦🇺AU_160 |11.34Mb
  - Relay_-🇮🇪IE_145 |304.26Mb
  - disney_KR |10.24Mb
  - disney_KR |10.70Mb
  - Relay_-🇯🇵JP_168 |12.23Mb
  - Relay_🇧🇬 BG-🇦🇺AU_171 |11.62Mb
  - disney_KR |10.79Mb
  - disney_netflix_PL |134.47Mb
  - Relay_🇭🇰HK-🇮🇩ID_180 |11.67Mb
  - disney_netflix_NL |27.88Mb
  - disney_netflix_HK |26.93Mb
  - netflix_JP |12.90Mb
  - Relay_🏁ZZ-🇰🇷KR_207 |28.32Mb
  - 🇰🇷KR_186 |112.60Mb
  - Relay_🇺🇸US-🇺🇸US_201 |32.21Mb
  - netflix_DK |25.13Mb
  - netflix_KR |12.77Mb
  - disney_TW |10.41Mb
  - Relay_🇺🇸US-🇮🇩ID_200 |11.53Mb
  - 🇭🇺HU_183 |28.34Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,🚀 节点选择
